{% set name = "ldas-tools-cmake" %}
{% set version = "1.2.0" %}
{% set sha256 = "8d8186609a9ad28acbd31a837f1dbc077d50171210d18cc1ab252fae20b1dbf6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - cmake >=3.2

test:
  requires:
    - pkg-config  # [unix]
  commands:
    - test -f ${PREFIX}/share/ldas-tools/cmake/Modules/LDASToolsInstallDirs.cmake  # [unix]
    - test -f ${PREFIX}/share/ldas-tools/cmake/Modules/Autotools/ArchiveX/cx_ldas_pkg_check.cmake  # [unix]
    - test "$(pkg-config --modversion ldastoolscmake)" == "{{ version }}"  # [unix]
    - if not exist %LIBRARY_PREFIX%\share\ldas-tools\cmake\Modules\LDASToolsInstallDirs.cmake exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\share\ldas-tools\cmake\Modules\Autotools\ArchiveX\cx_ldas_pkg_check.cmake exit 1  # [win]

about:
  home: https://git.ligo.org/ldastools/LDAS_Tools
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: CMake functions used by LDAS Tools

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
