{% set name = "ldas-tools-cmake" %}
{% set version = "1.3.0" %}

# dependency versions
{% set igwn_cmake_macros_version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
  sha256: 7dd0db9b228fe4c8978b1ce70ac67644b1d8429d5fca0f5e206e3df0a7a0cdb2

build:
  error_overdepending: true
  error_overlinking: true
  ignore_run_exports:
    # we don't actually use the compiler, but need it to configure cmake
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
  noarch: generic
  number: 1

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.2
    - make  # [unix]
    - pkg-config
  host:
    - igwn-cmake-macros >={{ igwn_cmake_macros_version }}
  run:
    - __unix  # [unix]
    - __win  # [win]
    - igwn-cmake-macros >={{ igwn_cmake_macros_version }}

test:
  requires:
    - pkg-config  # [unix]
  commands:
    # check files exist
    - test -f ${PREFIX}/share/ldas-tools/cmake/Modules/LDASToolsCMakeConfig.cmake  # [unix]
    - if not exist %LIBRARY_PREFIX%\share\ldas-tools\cmake\Modules\LDASToolsCMakeConfig.cmake exit 1  # [win]
    # check pkg-config
    - pkg-config --exact-version {{ version }} ldastoolscmake  # [unix]

about:
  home: https://wiki.ligo.org/Computing/LDASTools
  dev_url: https://git.ligo.org/ldastools/LDAS_Tools
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: CMake functions used by LDAS Tools
  description: |
    This collection of cmake macros was developed as part of
    the LDAS Tools Suite to have consistency across all of the packages

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
