schema_version: 1

context:
  name: ldas-tools-cmake
  version: "1.4.1"
  # dependency versions
  igwn_cmake_macros_version: 1.6.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: http://software.ligo.org/lscsoft/source/${{ name }}-${{ version }}.tar.gz
  sha256: 860289a286edb385bd96fc1fcb3ecc73f0424849bb62c67998b7dc435136217b
  patches:
    - boost-prefix.patch

build:
  noarch: generic
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake >=3.2
    - make
    - pkg-config
  host:
    - igwn-cmake-macros >=${{ igwn_cmake_macros_version }}
    - libboost-devel
  run:
    - igwn-cmake-macros >=${{ igwn_cmake_macros_version }}
  ignore_run_exports:
    by_name:
      - ${{ stdlib('c') }}
      - ${{ compiler('cxx') }}

tests:
  - package_contents:
      files:
        - share/ldas-tools/cmake/Modules/LDASToolsCMakeConfig.cmake
  - requirements:
      run:
        - pkg-config
    script:
      - pkg-config --exact-version ${{ version }} ldastoolscmake

about:
  summary: CMake functions used by LDAS Tools
  description: |
    This collection of cmake macros was developed as part of
    the LDAS Tools Suite to have consistency across all of the packages
  homepage: https://wiki.ligo.org/Computing/LDASTools
  repository: https://git.ligo.org/ldastools/LDAS_Tools
  license: GPL-2.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
