appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: A4xGN6oG8j4PbhX67FhNo9rSaOgAsXmKxA+f9pEKtJ0K0YdU9vkjWDtpa8j2GUgtSZEnisw0hbbFhgghOTZVY92DybcLwUi8jzIHR+7tK/BMjGL5yfD35sVBXF34RmJ0E8SGOMmHrfrJe+u3JJMUDd5ZNrs0aSmJQJWP6zy8Rpt/LXfIpqcjfQXR8g+4kJHH38V3jymd8XMB91sGwMSD12lpjKsCxaUP/uCbRK+ewIm2nKr9V2xuJ3MvOOgMAHrh9K+em8qUJVnf5YlS72qkO+2xX/83xy5acS/R8W/vQ/gRK2E6i6WORUGIdpwxqGAQ2miwIYGAINDC62BJDFSW41WlKUzj3cBIt1689aEU55k/35tF20rzAI9fYXoVDrc4mwaU6HPPg3nJBonYRkWPcuPCNm0Oy557Bfyh3Y5DvT7Aa8mX3LMTKTf5x2Es+mwSWkt+TAEs/7kd0bxrIVQDI69qqDsWs/ckYMYGePimg3S9fl4ZfWWvFSejPln+JbKI8HMo/P0t7nUzu+psNPbIdxEzWUJiWqYKsrMgaypFfQemHlUlCZjpsvZyHFh3n0QuBxvYKFqACM7d6IhBqZQmrQIY1aW2O7e/PAvbldXgdRqafQzkGzt2zQTLVeemBv+S/nPgG7ioN5z76GRnxN3gyCW8w8X6vUIS2Jpgatkm5FY=}
provider:
  win: azure
conda_forge_output_validation: true
